baseurl: "https://andygrunwald.com/"
languageCode: "en-us"
title: "Andy Grunwald"
theme: "hugo-type-theme"
googleAnalytics: "UA-64342623-1"
# Posts per page
paginate: 10
permalinks:
  post: /blog/:title/

privacy:
  googleAnalytics:
    anonymizeIP: true

SectionPagesMenu: "nav"

# Syntax highlighting
pygmentsCodeFences: true
pygmentsStyle: "friendly"

# Related content feature
related:
  threshold: 100
  includeNewer: true
  toLower: true
  indices:
    - name: keywords
      weight: 10
    - name: tags
      weight: 100

params:
  mainSections:
    - "post"
  author: "Andy Grunwald"
  description: "Andy Grunwald - Software Engineer from Germany"
  keywords: "backend,infrastructure,operations,devops,web development,web engineering"
  copyright: "Andy Grunwald"
  headerText: "Hi, my name is **Andy Grunwald**, a Software Engineer with a focus on **Backend, Infrastructure, and Culture**. I work at [trivago](https://www.trivago.com/) and run the [Web Engineering DUS Meetup](https://www.meetup.com/Web-Engineering-Duesseldorf/)."
  avatar: "img/avatar.jpeg"
  social:
    rss: true
    email: "andygrunwald@gmail.com"
    github: "andygrunwald"
    linkedin: "andy-grunwald-09aa265a"
    twitter: "andygrunwald"
    meetup: "Web-Engineering-Duesseldorf/"
    speakerdeck: "andygrunwald"

menu:
  nav:
    - Name: "Public speaking"
      Weight: -90
      Identifier: "public-speaking"
      URL: "/public-speaking/"
    - Name: "Blog"
      Weight: -100
      Identifier: "post"
      URL: "/"