baseurl: "https://andygrunwald.com/"
languageCode: "en-us"
defaultContentLanguage: en
disableHugoGeneratorInject: true
title: "Andy Grunwald"
theme: "hugo-type-theme"
googleAnalytics: "UA-64342623-1"
# Posts per page
paginate: 10
permalinks:
  post: /blog/:title/

privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  disqus:
    disable: true

SectionPagesMenu: "nav"

enableEmoji: true
enableRobotsTXT: true
canonifyURLs: true

# Syntax highlighting
pygmentsCodeFences: true
pygmentsStyle: "friendly"

# Related content feature
related:
  threshold: 100
  includeNewer: true
  toLower: true
  indices:
    - name: keywords
      weight: 10
    - name: tags
      weight: 100

params:
  mainSections:
  - "post"
  author: "Andy Grunwald"
  description: "Andy Grunwald - Software Engineer and Engineering Culture"
  keywords: "backend, infrastructure, scalability, operations, devops, engineering culture, web development, web engineering"
  copyright: "Andy Grunwald"
  headerText: "Hi, my name is **Andy Grunwald**, a Software Engineer with a focus on **Backend, Infrastructure, and Engineering Culture**. I work at [trivago](https://www.trivago.com/) and run the [Web Engineering DUS Meetup](https://www.meetup.com/Web-Engineering-Duesseldorf/)."
  avatar: "img/avatar.png"
  social:
    rss: true
    email: "andygrunwald@gmail.com"
    github: "andygrunwald"
    linkedin: "andy-grunwald-09aa265a"
    twitter: "andygrunwald"
    meetup: "Web-Engineering-Duesseldorf/"

menu:
  nav:
    # TODO Get the Public Speaking Section working again. See README.md for more information.
    #- Name: "Public speaking"
    #  Weight: -90
    #  Identifier: "public-speaking"
    #  URL: "/public-speaking/"
    - Name: "Blog"
      Weight: -100
      Identifier: "post"
      URL: "/"